<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>
	
	<?php echo $this->navigation()->links(Zend_Registry::get('navigation')).PHP_EOL; ?>
	
	<?php $this->headTitle()->setSeparator(' - '); ?>
	<?php $this->headTitle('My WebSite'); ?>
	<?php echo $this->headTitle().PHP_EOL; ?>
	
	<?php $this->headLink()->appendStylesheet('/css/style.css','all'); ?>
	<?php $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Leckerli+One','all'); ?>
	<?php $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Yellowtail','all'); ?>
	<?php $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Nova+Square','all'); ?>
	<?php echo $this->headLink();?>
</head>
<body id="body">
<div id="top">
	<div id="top_content">
		<div id="logo">
			<h1>Title 1</h1>
			<h4>Title 4</h4>
		</div>
	</div>
</div>
<div class="menu">
	<div class="menu_content">
		<?php echo $this->navigation()->menu(Zend_Registry::get('navigation'));?>
	</div>
</div>
<div class="breadcrumbs">
	<a class="first" href="/index">My WebSite</a> &rarr;
	<?php echo $this->navigation()
	                    ->breadcrumbs(Zend_Registry::get('navigation'))
	                    ->setSeparator(' &rarr; ')
	                    ->setMinDepth(0); ?>
</div>
<div id="video">
	<div id="video_content">
			<h2>Title 2</h2>
			<h3>Title 3</h3>
	</div>
</div>
<div id="content">
	<?php echo $this->layout()->content;?>
</div>
<div id="bottom">
	<div id="bottom_content">
		<div class="callcenter">
			<p class="call_us" style="color:#e44038;padding-left:30px;">Suport 24/7: </p>
			<p class="call_us"><img src="img/phone.png" alt="phone" />  (045)0205968600 or (045)0205968611</p>
			<p class="call_us"><img src="img/email.png" alt="email" />  contact@contact.com</p>

		</div>
		<div id="menu_bottom_list">
				<div class="menu_bottom" ><a href="" class="bottom_link" > Home </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> Try it </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> Download </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> Documentation </a></div>
				<div class="menu_bottom" ><a href="" class="bottom_link"> About </a></div>
		</div>
		<div class="copyright description">&copy; 2011 Ioana Condor
		</div>
	</div>
</div>
</body>
</html>